name: "release"

on:
  push:
    branches:
      - "prod"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm ci

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.GITHUB_SHA }}"
          prerelease: false
          title: "Production Build"
          files: |
            README.md
            *.js
